var i18n = {
  current_language: 'en',
  js_clone_public_map: 'Clone public map',
  js_do_you_want_to_clone_map_to_account: 'Do you want to copy this mind map to your account?',
  js_reactivation_required: 'Reactivation required',
  js_change_email_requires_reactivation_are_u_sure: 'Changing your email address requires reactivation of your account via email.<br/>Do you want to continue?',
  js_please_note_browser_not_supported: 'Please note that your browser isn\'t fully supported yet - you may experience some strange effects...',
  js_create_as_map: 'Create as Map',
  js_create_as_map_explanation: 'This will create a new map from the selected idea and all child ideas will be moved to the new map.',
  js_create_as_map_add_link: 'Add link to new map',
  js_create_as_map_preserve_permissions: 'Preserve sharing permissions',
  js_text_outline_of: 'Text Outline of ',
  js_c_to_copy_content_to_clipboard: '-C to copy contents to your clipboard',
  js_remove_icon: 'Remove Icon',
  js_cut: 'Cut',
  js_copy: 'Copy',
  js_paste: 'Paste',
  js_copy_as_text: 'Copy as Text',
  js_edit: 'Edit',
  js_edit_caption: 'Edit Caption',
  js_note: 'Note',
  js_add_note: 'Add Note',
  js_edit_note: 'Edit Note',
  js_call_via_skype: 'Call via Skype',
  js_chat_via_skype: 'Chat via Skype',
  js_start_skype_conference: 'Start Skype Conference',
  js_view_profile: 'View Profile',
  js_no_auto_note_found_for_topic: 'No WunderNote found for topic',
  js_getting_auto_link: 'getting WunderLink',
  js_no_link_found_for_topic_timeout: 'No WunderLink found for topic - operation timed out',
  js_no_link_found_for_topic: 'No WunderLink found for topic',
  js_no_attachments: 'No attachments',
  js_remove_attachment: 'Remove attachment',
  js_remove: 'Remove',
  js_open: 'Open',
  js_duplicate: 'Duplicate',
  js_delete: 'Delete',
  js_share: 'Share',
  js_preview: 'Preview',
  js_export: 'Export',
  js_properties: 'Properties',
  js_preview_of: 'Preview of',
  js_delete_mind_map: 'Delete Mind Map',
  js_you_are_about_to_delete: 'You are about to delete',
  js_do_you_want_to_continue: 'Do you want to continue?',
  js_find: 'Find:',
  js_january: 'January',
  js_february: 'February',
  js_march: 'March',
  js_april: 'April',
  js_may: 'May',
  js_june: 'June',
  js_july: 'July',
  js_august: 'August',
  js_september: 'September',
  js_octomber: 'October',
  js_november: 'November',
  js_december: 'December',
  js_critical_error_occured: 'A critical error has occured in MindMeister.',
  js_event_logged_and_error_will_be_corected: 'We\'re sorry for the inconvenience, the event has been logged and the error will be corrected as soon as possible.',
  js_this_map_cant_be_initialized: 'This map cannot be initialized',
  js_press_ok_to_reload_page: 'Please press OK to reload the page.',
  js_status_updating_changes_from_server: 'Status: updating changes from server',
  js_status_idle: 'Status: idle',
  js_entering_brainstorming_mode: 'Entering brainstorming mode',
  js_you_are_in_view_only_mode: 'You are in view only mode',
  js_other_users_editing: ' - other users are currently editing',
  js_copied_to_clipboard: 'Copied to clipboard',
  js_none: 'None',
  js_not_started: 'Not started',
  js_complete: 'Complete',
  js_done_lower: 'done',
  js_edit_label: 'Edit label',
  js_cant_copy_into_self_or_children: 'Cannot copy into self or children!',
  js_you_need_to_allow_this_page_to_use_google_gears_to_enable_offline_functionality: 'You need to allow this page to use Google Gears to enable offline functionality, or %s.',
  js_switch_off_offline_mode: 'disable offline mode',
  js_error_encountered_when_taking_maps_offline: 'Error encountered when taking maps offline!',
  js_you_are_not_connected_to_internet_connect_and_try_again: 'You are not connected to the internet. Please connect and try again.',
  js_error_encountered_when_putting_maps_online: 'Error encountered when putting maps back online.',
  js_wrong_password_please_try_again: 'Wrong password - please try again',
  js_you_are_working_offline_now_can_edit_and_create_new_maps: 'You are working offline now. You can edit all available maps as well as create new maps.',
  js_certain_features_may_not_be_available: 'Certain features may not be available',
  js_title: 'Title',
  js_created_by: 'Created by',
  js_shared_with: 'Shared with',
  js_last_modified: 'Last modified',
  js_please_wait_for_map_synchronization: 'Please wait for map synchronization',
  js_please_wait_for_attachments_synchronization: 'Please wait for attachments upload',
  js_you_should_leave_this_windows_open_to_avoid_damaging_your_maps: 'You should leave this window open during synchronization to avoid damaging your maps',
  js_taking_s_maps_offline_s: 'Taking %s maps ',
  js_taking_s_attachments_offline_s: 'Taking %s attachments online',
  js_conflict_detected_on: 'Conflict detected on ',
  js_map_modified_online_please_choose_action: ' The map was modified on the server while you were offline. Please choose one of the options below.',
  js_discard_changes: 'Discard changes',
  js_save_as_new_map: 'Save as new map',
  js_install_google_gears: 'Install Google Gears',
  js_offline_enable_google_gears_need_it_intall_now: 'You have enabled offline functionality, which requires Google Gears to be installed. Install now?',
  js_install_gears_to_use_mm_offline_features: 'Install google gears to use MindMeister\'s offline features.',
  js_error_commiting_offline_changes: 'Error committing offline changes',
  js_cant_go_online_we_are_sorry_force_online: 'There was a problem committing your changes. We\'re very sorry and are trying to fix the issue as soon as possible. Do you want to force going online now?',
  js_you_will_loose_all_press_no_end_export_first: 'You will lose all your offline changes (so you might want to press No and export changes as text first)',
  js_yes: 'Yes',
  js_no: 'No',
  js_connection_to_server_lost: 'Connection to server lost!',
  js_none_is_editing_on_this_map_now: 'No one else is editing this mind map',
  js_cant_delete_root_note: 'Cannot delete root node!',
  js_must_select_something_first: 'You have to select something first.',
  js_cant_move_root_note: 'You cannot move the root node.',
  js_must_select_destination: 'You have to select the destination.',
  js_must_cut_something_first: 'You have to cut something first.',
  js_cut_only_works_within_map: 'Please note that Cut and Paste only works within a map. Use Copy and Paste to move ideas between different maps.',
  js_cant_paste_in_same_tree: 'Cannot paste in same tree.',
  js_ambiguos_action: 'Ambiguous action.',
  js_please_select_an_idea_first: 'Please select an idea first',
  js_attachments: 'Attachments',
  js_task_information: 'Task Information',
  js_due_date: 'Due Date:',
  js_start_date: 'Start Date:',
  js_duration: 'Duration',
  js_assigned_to: 'Assigned To:',
  js_external_link: 'External link',
  js_about_thumbshot_thumbails: 'About Thumbshots thumbnails',
  js_email_link: 'Email link',
  js_link_to_topic: 'Link to topic',
  js_in_this_map: 'in this map',
  js_maximum_zoomlevel_reached: 'Maximum zoom level reached.',
  js_minimum_zoomlevel_reached: 'Minimum zoom level reached.',
  js_google_could_not_be_contacted: 'Google could not be contacted. Please try again later.',
  js_ok: 'OK',
  js_wrapper_text_warning: 'This will convert long nodes to the new persistent wrapping format in MindMeister 3.0. Press OK to proceed.',
  js_this_is_very_quick_u_can_undo_afterwards: 'This is very quick and you can undo all changes afterwards.',
  js_click_to_sign_in: 'Click to Sign In',
  js_topic: 'Topic',
  js_saving: 'Saving...',
  js_all_changes_are_save_automatically_no_need_to_save_manually: 'All changes to your mind map are saved automatically, so no need to save manually.',
  js_info: 'Info',
  js_warning: 'Warning',
  js_error: 'Error',
  js_did_you_know: 'Did you know?',
  js_click_to_edit: 'Click to edit',
  js_error_communicating_with_server: 'Error communicating with the server: ',
  js_january_short: 'Jan',
  js_february_short: 'Feb',
  js_march_short: 'Mar',
  js_april_short: 'Apr',
  js_june_short: 'Jun',
  js_july_short: 'Jul',
  js_august_short: 'Aug',
  js_september_short: 'Sep',
  js_octomber_short: 'Oct',
  js_november_short: 'Nov',
  js_december_short: 'Dec',
  js_sunday: 'Sunday',
  js_monday: 'Monday',
  js_tuesday: 'Tuesday',
  js_wednesday: 'Wednesday',
  js_thursday: 'Thursday',
  js_friday: 'Friday',
  js_saturday: 'Saturday',
  js_sunday_short: 'Sun',
  js_monday_short: 'Mon',
  js_tuesday_short: 'Tue',
  js_wednesday_short: 'Wed',
  js_thursday_short: 'Thu',
  js_friday_short: 'Fri',
  js_saturday_short: 'Sat',
  js_public_map: ' (PUBLIC)',
  js_view_only_map: ' (VIEW ONLY)',
  js_priority: 'Priority',
  js_node_copied_unavailable: 'The node you copied is not available anymore',
  js_node_cut_unavailable: 'The node you cut is not available anymore',
  js_you_cant_do_that_now: 'Sorry, you can\'t do that now.',
  js_the_following_attachments_failed: 'The following attachments could not be taken online:',
  js_no_internet_connection_available_now: 'This action requires internet connection and no internet connection is available to you at the moment',
  js_invalid_attachment: 'Invalid attachment uploaded!',
  js_invalid_attachment_will_be_removed: 'This attachment is invalid (exceeds size), it was removed from your node. Please try again with another file.',
  js_invalid_task_date: 'Invalid due date for task. Please set a valid date for this task',
  js_user_has_no_skype_account_or_has_not_provided_one: 'This user has no Skype account, or has not provided a Skype name on his/her profile.',
  js_map_saved: 'Map saved...',
  js_invalid_link: 'Invalid link: ',
  js_there_are_no_revisions_for_this_map_it_was_not_modified_yet: 'There are no revisions for this mind map. Most likely it was not modified yet.',
  js_external_save_successful: 'Changes to your map saved successfully!',
  js_external_save_failed: 'Failed to save changes to your map',
  js_your_request_was_not_done: 'Request failed',
  js_we_are_sorry_request_was_not_done: 'We\'re sorry, but your request was not completed this time. An error occurred. Please try again.',
  js_errors_occured_while_getting_changes: 'Errors occured while getting the changes from the server.',
  js_helper_hours: 'hours',
  js_helper_days: 'days',
  js_helper_weeks: 'weeks',
  js_helper_months: 'months',
  js_pay_paypal: 'Go to PayPal and complete order',
  js_pay_creditcard: 'Finish',
  js_gears_feature_unavailable_on_this_browser: 'Google Gears does not support this feature on your browser yet.',
  js_history_inserted: ' inserted <em class="change">%s</em>',
  js_history_renamed: ' renamed <em class="change">%s</em> to <em class="change">%s</em>',
  js_history_removed: ' removed <em class="change">%s</em>',
  js_history_repositioned: ' repositioned <em class="change">%s</em>',
  js_history_moved: ' moved <em class="change">%s</em>',
  js_history_removed_icon_from: ' removed an icon from <em class="change">%s</em>',
  js_history_added_icon_to: ' added an icon to <em class="change">%s</em>',
  js_history_added_text_style_to: ' added a text style to <em class="change">%s</em>',
  js_history_added_note_to: ' added a note to <em class="change">%s</em>',
  js_history_removed_note_from: ' removed the note from <em class="change">%s</em>',
  js_history_added_link_to: ' added a link to <em class="change">%s</em>',
  js_history_removed_task_from: ' removed the task from <em class="change">%s</em>',
  js_history_added_task_to: ' added a task to <em class="change">%s</em>',
  js_history_added_attachment_to: ' added an attachment to <em class="change">%s</em>',
  js_history_removed_attachment_from: ' removed an attachment from <em class="change">%s</em>',
  js_history_added_connection: ' added a connection from <em class="change">%s</em> to <em class="change">%s</em>',
  js_history_removed_connection: ' removed the connection from <em class="change">%s</em> to <em class="change">%s</em>',
  js_history_created_the_map: ' created the map',
  js_you_still_have_tasks_sure_want_to_withdraw: 'You still have tasks assigned in this mind map. Are you sure you want to withdraw?',
  js_s_still_has_tasks_sure_want_to_remove_s: '%s still has tasks assigned in this mind map. Are you sure you want to remove %s from the sharing list?',
  js_removing_collaborator: 'Removing collaborator',
  js_inaccessible_map: 'Inaccessible Map',
  js_map_not_share_with_u_anymore_contact_s: 'This map is not shared with you anymore. Please contact the owner %s and ask them to share it with you again.',
  js_withraw_from_map: 'Withdraw from map',
  js_you_are_about_to_withdraw: 'You are about to withdraw from',
  js_history_added_image_to_s: ' added an image to <em class="change">%s</em>',
  js_history_removed_image_from_s: ' removed the image from <em class="change">%s</em>',
  js_history_resized_image_on_s: ' resized image on <em class="change">%s</em>',
  js_node_has_no_image: 'Selected node has no image',
  js_image_could_not_be_found: 'Image could not be found',
  js_upload_new_image: 'Upload a new image...',
  js_use_an_image_from_the_web: 'Use an image from the web...',
  js_browse_image_library: 'Browse image library...',
  js_mindmeister_default: 'Mindmeister Default',
  js_recent_icons: 'Recent Icons',
  js_you_may_want_to_dot_dot_dot: 'You may want to...',
  js_no_default_images: 'No default images',
  js_no_image_selected: 'You have to select an image first',
  js_no_image_was_found: 'No images found - please try and shorten your search terms',
  js_no_auto_image_was_found: 'No WunderBild found for topic',
  js_browse_icon_library: 'Browse icon library...',
  js_images_s: '%s images',
  js_icons_s: '%s icons',
  js_history_edited_note_on: ' edited the note on <em class="change">%s</em>',
  js_history_edited_task_on: ' edited the task on <em class="change">%s</em>',
  js_history_removed_link_from: ' removed link from <em class="change">%s</em>',
  js_history_edited_link_on: ' edited the link on <em class="change">%s</em>',
  js_priority_s: 'Priority %s',
  js_cancel: 'Cancel',
  js_go_offline: 'go offline',
  js_use_offline_mode: 'use the offline mode',
  js_new_node: 'New node',
  js_one_child_idea: 'One child idea',
  js_more_child_ideas_d: '%d child ideas',
  js_direct_link: 'Direct link',
  js_show_detail: 'Show Detail',
  js_apply_to_branch: 'Apply to Branch',
  js_tools: 'Tools',
  js_one_level: 'One Level',
  js_two_levels: 'Two Levels',
  js_all: 'All',
  js_color: 'Color',
  js_font_size: 'Font Size',
  js_font_style: 'Font Style',
  js_alphabetize: 'Alphabetize',
  js_image_unavailable: 'Image unavailable',
  js_load_more_dot_dot_dot: 'load more...',
  js_no_images: 'No images',
  js_images_d: '%d images',
  js_google_cannot_be_contacted: 'You are not working offline. Google cannot be contacted.',
  js_image_not_available: 'Image not available',
  js_history_changed_an_icon_s: ' changed an icon on <em class="change">%s</em>',
  js_history_set_the_priority_of_a_task_to_s_s: ' set the priority of <em class="change">%s</em> to %s',
  js_task_view_on: 'Task view on',
  js_connect_node_to_itself: 'Cannot connect a node to itself.',
  js_links: 'Links',
  js_tasks: 'Tasks',
  js_extras: 'Extras',
  js_notes: 'Notes',
  js_history_set_a_task_to_completed_d_s: ' set the task <em class="change">%s</em> to %s completed',
  js_click_to_filter_by_this_user: 'Click to filter changes by this user',
  js_click_to_filter_by_this_idea: 'Click to filter changes by this idea',
  js_view_changes_on_this_idea: 'View Changes...',
  js_support_for_ie6_over_s: 'Please note that MindMeister works best with recent browsers such as <a href="%s" target="_blank">Internet Explorer 7/8</a>, or better still, <a href="%s" target="_blank">Firefox</a>.',
  js_map_contains_unconverted_long_nodes_lets_wrap: 'This mind map contains unconverted long nodes. Press Alt-F10 to convert them to the new persistent wrapping format.',
  js_history_changed_connection_color: ' changed connection color from <em class="change">%s</em> to <em class="change">%s</em>',
  js_contact_owner_link_s: '<a class="plainlink" href="%s">Contact owner</a>',
  js_this_image_is_subject_to_copyright: 'This image is subject to copyright',
  js_this_image_may_be_subject_to_copyright: 'This image may be subject to copyright',
  js_open_source_page: 'View on source page',
  js_checking_image_license: 'Checking for image license...',
  js_no_icon_selected: 'You have to select an icon first',
  js_image_does_not_match: 'Image does not match',
  js_loading_image: 'Loading image',
  js_network_problem: '\'Network problem. Cannot contact server.\'',
  js_start_date_is_set_after_due_date: 'Start date is set after the due date',
  js_offline_word: 'offline',
  js_me: 'Me',
  js_do_u_want_to_save_the_changes: 'Do you want to save your changes before leaving the editor?',
  js_background_color: 'Background Color',
  js_box_style: 'Box Style',
  js_you_cannot_use_undo_redo_in_collaborative_mode: 'You need to leave brainstorming mode to be able to undo changes safely and avoid concurrency conflicts.',
  js_cancel_invitations_warning: 'Invitations will not be sent - please confirm.',
  js_no_results_received: 'No results received',
  js_revert_to_revision_warning: 'All changes since revision %s will be irreversibly lost. Are you sure you want to continue?',
  js_cloned_revision: 'The current revision has been saved as a new mind map in your maps list.',
  js_group_chat: 'Group chat',
  js_older_messages: 'Show earlier messages'
}