package org.qaf.sifarnici.model;

// Generated Jan 30, 2010 12:08:20 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.qaf.common.model.BaseEntity;


/**
 * Bolnica generated by hbm2java
 */
@Entity
@Table(schema="qaf", name = "bolnica", uniqueConstraints = {})
public class Bolnica extends BaseEntity implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 0L;

	private int id;

	private String naziv;

	private String adresa;

	private Date uneto;

	private boolean vazeci;

	// Constructors

	/** default constructor */
	public Bolnica() {
	}

	/** minimal constructor */
	public Bolnica(int id, String naziv, Date uneto, boolean vazeci) {
		this.id = id;
		this.naziv = naziv;
		this.uneto = uneto;
		this.vazeci = vazeci;
	}

	/** full constructor */
	public Bolnica(int id, String naziv, String adresa, Date uneto,
			boolean vazeci) {
		this.id = id;
		this.naziv = naziv;
		this.adresa = adresa;
		this.uneto = uneto;
		this.vazeci = vazeci;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "naziv", unique = false, nullable = false, insertable = true, updatable = true)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "adresa", unique = false, nullable = true, insertable = true, updatable = true)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "uneto", unique = false, nullable = false, insertable = true, updatable = true, length = 35)
	public Date getUneto() {
		return this.uneto;
	}

	public void setUneto(Date uneto) {
		this.uneto = uneto;
	}

	@Column(name = "vazeci", unique = false, nullable = false, insertable = true, updatable = true)
	public boolean isVazeci() {
		return this.vazeci;
	}

	public void setVazeci(boolean vazeci) {
		this.vazeci = vazeci;
	}

}
