package org.qaf.sifarnici.model;

// Generated Jan 30, 2010 12:08:20 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.qaf.common.model.BaseEntity;


/**
 * Pacijent generated by hbm2java
 */
@Entity
@Table(schema="medis", name = "pacijent", uniqueConstraints = {})
public class Pacijent extends BaseEntity implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private int id;

	private String ime;

	private String prezime;

	private String adresa;

	private Date datumRodjenja;

	private Boolean vazeci;

	// Constructors

	/** default constructor */
	public Pacijent() {
	}

	/** minimal constructor */
	public Pacijent(int id, String ime, String prezime, String adresa) {
		this.id = id;
		this.ime = ime;
		this.prezime = prezime;
		this.adresa = adresa;
	}

	/** full constructor */
	public Pacijent(int id, String ime, String prezime, String adresa,
			Date datumRodjenja, Boolean vazeci) {
		this.id = id;
		this.ime = ime;
		this.prezime = prezime;
		this.adresa = adresa;
		this.datumRodjenja = datumRodjenja;
		this.vazeci = vazeci;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ime", unique = false, nullable = false, insertable = true, updatable = true)
	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	@Column(name = "prezime", unique = false, nullable = false, insertable = true, updatable = true)
	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	@Column(name = "adresa", unique = false, nullable = false, insertable = true, updatable = true)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "datum_rodjenja", unique = false, nullable = true, insertable = true, updatable = true, length = 35)
	public Date getDatumRodjenja() {
		return this.datumRodjenja;
	}

	public void setDatumRodjenja(Date datumRodjenja) {
		this.datumRodjenja = datumRodjenja;
	}

	@Column(name = "vazeci", unique = false, nullable = true, insertable = true, updatable = true)
	public Boolean getVazeci() {
		return this.vazeci;
	}

	public void setVazeci(Boolean vazeci) {
		this.vazeci = vazeci;
	}

}
