package org.qaf.waf.content.model;

// Generated Feb 6, 2010 11:07:02 PM by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.qaf.common.model.BaseEntity;


/**
 * Grupaaplikacija generated by hbm2java
 */
@Entity
@Table(schema="admin", name = "grupaaplikacija", uniqueConstraints = {})
public class Grupaaplikacija extends BaseEntity implements java.io.Serializable {

	// Fields

	private int id;

	private String naziv;

	private short vazeci;

	// Constructors

	/** default constructor */
	public Grupaaplikacija() {
	}

	/** full constructor */
	public Grupaaplikacija(int id, String naziv, short vazeci) {
		this.id = id;
		this.naziv = naziv;
		this.vazeci = vazeci;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "naziv", unique = false, nullable = false, insertable = true, updatable = true)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "vazeci", unique = false, nullable = false, insertable = true, updatable = true)
	public short getVazeci() {
		return this.vazeci;
	}

	public void setVazeci(short vazeci) {
		this.vazeci = vazeci;
	}

}
