package org.qaf.waf.content.model;

// Generated Feb 6, 2010 11:07:02 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.CascadeType;
import org.qaf.common.model.BaseEntity;


/**
 * Modul generated by hbm2java
 */
@Entity
@Table(schema="admin", name = "modul", uniqueConstraints = {})
public class Modul extends BaseEntity implements java.io.Serializable {

	// Fields

	private int id;

	private String naziv;

	private Short vazeci;

	private Set<ModulAplikacija> modulAplikacije = new HashSet<ModulAplikacija>(0);

	// Constructors

	/** default constructor */
	public Modul() {
	}

	/** minimal constructor */
	public Modul(int id, String naziv) {
		this.id = id;
		this.naziv = naziv;
	}

	/** full constructor */
	public Modul(int id, String naziv, Short vazeci) {
		this.id = id;
		this.naziv = naziv;
		this.vazeci = vazeci;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "naziv", unique = false, nullable = false, insertable = true, updatable = true)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "vazeci", unique = false, nullable = true, insertable = true, updatable = true)
	public Short getVazeci() {
		return this.vazeci;
	}

	public void setVazeci(Short vazeci) {
		this.vazeci = vazeci;
	}

	@OneToMany
    @JoinColumn(name="modul_id")
    public Set<ModulAplikacija> getModulAplikacije() {
        return this.modulAplikacije;
    }

    public void setModulAplikacije(Set<ModulAplikacija> modulAplikacije) {
        this.modulAplikacije = modulAplikacije;
    }

}
