package org.qaf.security.model;

// Generated Feb 9, 2010 8:52:41 AM by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KorisnikUloga generated by hbm2java
 */
@Entity
@Table(schema="admin", name = "\"korisnik-uloga\"", uniqueConstraints = {})
public class KorisnikUloga implements java.io.Serializable {

	// Fields

	private int id;

	private int korisnikId;

	private int ulogaId;

	// Constructors

	/** default constructor */
	public KorisnikUloga() {
	}

	/** full constructor */
	public KorisnikUloga(int id, int korisnikId, int ulogaId) {
		this.id = id;
		this.korisnikId = korisnikId;
		this.ulogaId = ulogaId;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "korisnik_id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getKorisnikId() {
		return this.korisnikId;
	}

	public void setKorisnikId(int korisnikId) {
		this.korisnikId = korisnikId;
	}

	@Column(name = "uloga_id", unique = false, nullable = false, insertable = true, updatable = true)
	public int getUlogaId() {
		return this.ulogaId;
	}

	public void setUlogaId(int ulogaId) {
		this.ulogaId = ulogaId;
	}

}
