package org.qaf.security.model;

// Generated Feb 9, 2010 8:52:41 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.qaf.common.model.BaseEntity;


/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(schema="admin", name = "korisnik", uniqueConstraints = {})
public class Korisnik extends BaseEntity implements java.io.Serializable {

	// Fields
	/**
	 *
	 */
	private static final long serialVersionUID = -6450055467886737878L;

	private int id;

	private String korisnickoIme;

	private String lozinka;

	private String email;

	private String tokenPrivremeni;

	private String tokenTrajni;

	private String tokenSso;

	private Integer loginUspesanPuta;

	private Integer loginNeuspesanPuta;

	private Date ulogovanOd;

	private Date poslednjiZahtev;

	private Date poslednjiLogin;

	private String trenutniLoginIp;

	private String poslednjiLoginIp;

	private Integer uneo;

	private Date datumUnosa;

	private Set<Opiduser> opidusers = new HashSet<Opiduser>(0);

	// Constructors

	/** default constructor */
	public Korisnik() {
	}

	/** minimal constructor */
	public Korisnik(int id, String korisnickoIme, String lozinka) {
		this.id = id;
		this.korisnickoIme = korisnickoIme;
		this.lozinka = lozinka;
	}

	/** full constructor */
	public Korisnik(int id, String korisnickoIme, String lozinka, String email,
			String tokenPrivremeni, String tokenTrajni, String tokenSso,
			Integer loginUspesanPuta, Integer loginNeuspesanPuta,
			Date ulogovanOd, Date poslednjiZahtev, Date poslednjiLogin,
			String trenutniLoginIp, String poslednjiLoginIp, Integer uneo,
			Date datumUnosa, Set<Opiduser> opidusers) {
		this.id = id;
		this.korisnickoIme = korisnickoIme;
		this.lozinka = lozinka;
		this.email = email;
		this.tokenPrivremeni = tokenPrivremeni;
		this.tokenTrajni = tokenTrajni;
		this.tokenSso = tokenSso;
		this.loginUspesanPuta = loginUspesanPuta;
		this.loginNeuspesanPuta = loginNeuspesanPuta;
		this.ulogovanOd = ulogovanOd;
		this.poslednjiZahtev = poslednjiZahtev;
		this.poslednjiLogin = poslednjiLogin;
		this.trenutniLoginIp = trenutniLoginIp;
		this.poslednjiLoginIp = poslednjiLoginIp;
		this.uneo = uneo;
		this.datumUnosa = datumUnosa;
		this.opidusers = opidusers;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	@SequenceGenerator(name="my_seq", sequenceName="korisnik_id_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="my_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "korisnicko_ime", unique = false, nullable = false, insertable = true, updatable = true)
	public String getKorisnickoIme() {
		return this.korisnickoIme;
	}

	public void setKorisnickoIme(String korisnickoIme) {
		this.korisnickoIme = korisnickoIme;
	}

	@Column(name = "lozinka", unique = false, nullable = false, insertable = true, updatable = true)
	public String getLozinka() {
		return this.lozinka;
	}

	public void setLozinka(String lozinka) {
		this.lozinka = lozinka;
	}

	@Column(name = "email", unique = false, nullable = true, insertable = true, updatable = true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "token_privremeni", unique = false, nullable = true, insertable = true, updatable = true)
	public String getTokenPrivremeni() {
		return this.tokenPrivremeni;
	}

	public void setTokenPrivremeni(String tokenPrivremeni) {
		this.tokenPrivremeni = tokenPrivremeni;
	}

	@Column(name = "token_trajni", unique = false, nullable = true, insertable = true, updatable = true)
	public String getTokenTrajni() {
		return this.tokenTrajni;
	}

	public void setTokenTrajni(String tokenTrajni) {
		this.tokenTrajni = tokenTrajni;
	}

	@Column(name = "token_sso", unique = false, nullable = true, insertable = true, updatable = true)
	public String getTokenSso() {
		return this.tokenSso;
	}

	public void setTokenSso(String tokenSso) {
		this.tokenSso = tokenSso;
	}

	@Column(name = "login_uspesan_puta", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getLoginUspesanPuta() {
		return this.loginUspesanPuta;
	}

	public void setLoginUspesanPuta(Integer loginUspesanPuta) {
		this.loginUspesanPuta = loginUspesanPuta;
	}

	@Column(name = "login_neuspesan_puta", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getLoginNeuspesanPuta() {
		return this.loginNeuspesanPuta;
	}

	public void setLoginNeuspesanPuta(Integer loginNeuspesanPuta) {
		this.loginNeuspesanPuta = loginNeuspesanPuta;
	}

	@Column(name = "ulogovan_od", unique = false, nullable = true, insertable = true, updatable = true, length = 35)
	public Date getUlogovanOd() {
		return this.ulogovanOd;
	}

	public void setUlogovanOd(Date ulogovanOd) {
		this.ulogovanOd = ulogovanOd;
	}

	@Column(name = "poslednji_zahtev", unique = false, nullable = true, insertable = true, updatable = true, length = 35)
	public Date getPoslednjiZahtev() {
		return this.poslednjiZahtev;
	}

	public void setPoslednjiZahtev(Date poslednjiZahtev) {
		this.poslednjiZahtev = poslednjiZahtev;
	}

	@Column(name = "poslednji_login", unique = false, nullable = true, insertable = true, updatable = true, length = 35)
	public Date getPoslednjiLogin() {
		return this.poslednjiLogin;
	}

	public void setPoslednjiLogin(Date poslednjiLogin) {
		this.poslednjiLogin = poslednjiLogin;
	}

	@Column(name = "trenutni_login_ip", unique = false, nullable = true, insertable = true, updatable = true)
	public String getTrenutniLoginIp() {
		return this.trenutniLoginIp;
	}

	public void setTrenutniLoginIp(String trenutniLoginIp) {
		this.trenutniLoginIp = trenutniLoginIp;
	}

	@Column(name = "poslednji_login_ip", unique = false, nullable = true, insertable = true, updatable = true)
	public String getPoslednjiLoginIp() {
		return this.poslednjiLoginIp;
	}

	public void setPoslednjiLoginIp(String poslednjiLoginIp) {
		this.poslednjiLoginIp = poslednjiLoginIp;
	}

	@Column(name = "uneo", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getUneo() {
		return this.uneo;
	}

	public void setUneo(Integer uneo) {
		this.uneo = uneo;
	}

	@Column(name = "datum_unosa", unique = false, nullable = true, insertable = true, updatable = true, length = 35)
	public Date getDatumUnosa() {
		return this.datumUnosa;
	}

	public void setDatumUnosa(Date datumUnosa) {
		this.datumUnosa = datumUnosa;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "korisnik")
	public Set<Opiduser> getOpidusers() {
		return this.opidusers;
	}

	public void setOpidusers(Set<Opiduser> opidusers) {
		this.opidusers = opidusers;
	}

}
